version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN} # telegram token
      WEBSOCKET_PORT: 8081
      START_COMMAND_REPLY_TEXT: './src/assets/hello.txt'
      START_COMMAND_REPLY_VOICE: './src/assets/hello.oga'
      START_COMMAND_REPLY_PHOTO: './src/assets/hello.jpg'
    ports:
      - 8081:8081
    restart: unless-stopped
  mygirl:
    build:
      context: .
      dockerfile: Dockerfile_mygirl
    container_name: mygirl
    environment:
      WEBSOCKET_SERVER: http://bot:8081
      GPT_SERVER: "OPENAI API ADDRESS OF TEXT-GENERATION-WEBUI"
      TTS_SERVER: "ADDRESS FOR TTS"
      REDIS_SERVER: "ADDRESS OF REDIS" # alternative
    ports:
      - 8081:8081
    restart: unless-stopped